### ISSUE TITLE
Terminal setup details

### ISSUE THREAD

**Issue by willsoto** [stephenway/atelier-ocean#1]
Would you be able to share what terminal / theme you are using? Thanks in advance!

**Comment by stephenway** [comment]
See #2

**Comment by willsoto** [comment]
Sorry, I was unclear. I meant in terms of whether or not you are using
oh-my-zsh, what themes that is, etc.

**Comment by stephenway** [comment]
Oh yea, i used that a long time ago, but felt it was too heavy on load so I played around in regular zsh for a while, then fish, then back to bash because it seems to have the least resistance to my tooling due to syntax support. Theme is setup for base16 right now. You can check out my dotfiles here https://github.com/stephenway/sysconfig

I use iTerm for a very small reason, and this may not apply to you if your not into vim much, but simply love that my cursor is white and inverts the text it's on to black. You can make terminal get close, but not dynamic enough for contrast.

**Comment by willsoto** [comment]
Thanks for that! I am looking for the prompt in particular, but I can't seem to find it. When you have a chance, could you point me in the right direction if it is there?

Thanks in advance!

**Comment by stephenway** [comment]
Prompt
https://github.com/stephenway/sysconfig/blob/master/bash_profile#L64

relies on these functions
https://github.com/stephenway/sysconfig/blob/master/bashrc#L126

**Comment by willsoto** [comment]
Awesome! Thanks
